services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=birthdaydba
    volumes:
      - pgdata:/var/lib/postgresq/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
