spring:
  application:
    name: BirthdayNotifierAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/birthdaydba
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  mail:
    host: smtp.gmail.com
    port: 587
    username: maxloversist@gmail.com
    password: rwxx ftzg aung yctu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
