spring:
  application:
    name: BirthdayNotifierAPI
  datasource:
    url: jdbc:mysql://localhost:3306/birthdaydba
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[format_sql]": true
  mail:
    host: smtp.gmail.com
    port: 587
    username: maxloversist@gmail.com
    password: rwxx ftzg aung yctu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
